#!/bin/sh
PRG="$0"

while [ -h "$PRG" ]; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '.*/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

# Get standard environment variables

PRGDIR=`dirname "$PRG"`
SERVER_HOME=`cd "$PRGDIR/.." ; pwd`

if [ -z "$JAVA_HOME" ]; then
  JAVA_HOME=$SERVER_HOME/jre
fi

# Get standard Java environment variables
if [ -r "$SERVER_HOME"/bin/setclasspath.sh ]; then
  BASEDIR="$SERVER_HOME"
  . "$SERVER_HOME"/bin/setclasspath.sh
else
  echo "Cannot find $SERVER_HOME/bin/setclasspath.sh"
  echo "This file is needed to run this program"
  exit 1
fi

for f in $SERVER_HOME/lib/*.jar; do
  CLASSPATH=${CLASSPATH}:$f;
done

if [ -d "$SERVER_HOME/conf" ]; then
  CLASSPATH=${CLASSPATH}:$SERVER_HOME/conf
fi

if [ "$1" = "" ] ; then
exec "Usage:  inchain_cli ( commands ... )"
fi

if [ "$1" != "" ] ; then
exec "$_RUNJAVA" $JAVA_OPTS -cp "$CLASSPATH" org.inchain.rpc.RPCClient "$@"
fi
