#!/bin/sh
PRG="$0"

while [ -h "$PRG" ]; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '.*/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

# Get standard environment variables

PRGDIR=`dirname "$PRG"`
SERVER_HOME=`cd "$PRGDIR/.." ; pwd`

# Get standard Java environment variables
if [ -r "$SERVER_HOME"/bin/setclasspath.sh ]; then
  BASEDIR="$SERVER_HOME"
  . "$SERVER_HOME"/bin/setclasspath.sh
else
  echo "Cannot find $SERVER_HOME/bin/setclasspath.sh"
  echo "This file is needed to run this program"
  exit 1
fi

# ----- Execute The Requested Command -----------------------------------------
echo "Using SERVER_HOME:   $SERVER_HOME"
echo "Using JAVA_HOME:       $JAVA_HOME"

if [ "$1" = "" ] ; then
exec "Usage:  inchain_cli ( commands ... )"
fi

if [ "$1" != "" ] ; then
exec "$_RUNJAVA" $JAVA_OPTS -cp "$CLASSPATH" org.inchain.rpc.RPCClient "$@"
fi
